### ISSUE TITLE
Verify and potentially unblock openmmforcefield pins

### ISSUE THREAD

**Issue by IAlibay** [conda-forge/openfe-feedstock#57]
Follow-up from iteration meeting 9th May 2024

Check that the ~= 0.11.2 is appropriate and see if we can install 0.13

**Comment by mikemhenry** [comment]
This was completed here https://github.com/conda-forge/openfe-feedstock/pull/58/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR36
